 using UnityEngine;
    using System.Collections;
    using System.Collections.Generic;
 
//    [System.Serializable]
//    public class AxleInfo {
//        public WheelCollider leftWheel;
//        public WheelCollider rightWheel;
//        public bool motor;
//        public bool steering;
//    }
         
    public class SimpleCarController : MonoBehaviour {
        //Handling
        public List<AxleInfo> axleInfos; 
        public float maxMotorTorque;
        public float maxSteeringAngle;
        public float brakeForce;

        public Vector3 centerOfMassCorrection;
        //Internal
        public bool controlled;
        bool braking;


        void Start()
        {
            GetComponent<Rigidbody>().centerOfMass = centerOfMassCorrection;
        }
         
        // finds the corresponding visual wheel
        // correctly applies the transform
        public void ApplyLocalPositionToVisuals(WheelCollider collider)
        {
            if (collider.transform.childCount == 0) {
                return;
            }
         
            Transform visualWheel = collider.transform.GetChild(0);
         
            Vector3 position;
            Quaternion rotation;
            collider.GetWorldPose(out position, out rotation);
         
            visualWheel.transform.position = position;
            visualWheel.transform.rotation = rotation;
        }
         
        public void FixedUpdate()
        {
            if (controlled)
            {
                float motor = maxMotorTorque * Input.GetAxis("Vertical");
                float steering = maxSteeringAngle * Input.GetAxis("Horizontal");
                if (Input.GetButton("Jump")) { braking = true; } else { braking = false; }

                foreach (AxleInfo axleInfo in axleInfos)
                {
                    if (axleInfo.steering)
                    {
                        axleInfo.leftWheel.steerAngle = steering;
                        axleInfo.rightWheel.steerAngle = steering;

                        

                    }
                    if (axleInfo.motor)
                    {
                        axleInfo.leftWheel.motorTorque = motor;
                        axleInfo.rightWheel.motorTorque = motor;
                    }

				//Braking
				if (braking)
				{
					axleInfo.leftWheel.brakeTorque = brakeForce;
					axleInfo.rightWheel.brakeTorque = brakeForce;
				}
				else
				{
					axleInfo.leftWheel.brakeTorque = 0;
					axleInfo.rightWheel.brakeTorque = 0;
				}

                    ApplyLocalPositionToVisuals(axleInfo.leftWheel);
                    ApplyLocalPositionToVisuals(axleInfo.rightWheel);
                }
            }
        }


    }